#ifndef PINS_H
#define PINS_H


// external hardware
#define PIN_EXT_LED             0
#define PIN_BUZZER              0
#define PIN_ENDSWITCH_GLOBAL    0



// 
#define STEPPER_1_ENDSWITCH_PIN 0
#define STEPPER_1_DIRECTION_PIN 0
#define STEPPER_1_PULSE_PIN     0
#define STEPPER_1_IS_INVERTED   0       

#define STEPPER_1_INIT_POS      500
#define STEPPER_1_RESET_SPEED   1500



// 
#define STEPPER_2_ENDSWITCH_PIN 0
#define STEPPER_2_DIRECTION_PIN 0
#define STEPPER_2_PULSE_PIN     0
#define STEPPER_2_IS_INVERTED   1

#define STEPPER_2_INIT_POS      500
#define STEPPER_2_RESET_SPEED   1500



// 
#define STEPPER_3_ENDSWITCH_PIN 0
#define STEPPER_3_DIRECTION_PIN 0
#define STEPPER_3_PULSE_PIN     0
#define STEPPER_3_IS_INVERTED   0 

#define STEPPER_3_INIT_POS      500
#define STEPPER_3_RESET_SPEED   1500



// 
#define STEPPER_4_ENDSWITCH_PIN 0
#define STEPPER_4_DIRECTION_PIN 0
#define STEPPER_4_PULSE_PIN     0
#define STEPPER_4_IS_INVERTED   1 

#define STEPPER_4_INIT_POS      500
#define STEPPER_4_RESET_SPEED   1500


#endif